version: "3.3"
services:
    tsuserver:
        build: .
        image: tsuserver
        ports:
            - 27017:27017
            - 27018:27018
        volumes:
            - ./storage:/app/storage
            - ./logs:/app/logs
            - ./config:/app/config
        restart: unless-stopped

